// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FilterState is the filter state for table filtering and export (same shape as frontend).
 */
export class FilterState {
    "keyText": string;
    "keyMatchMode": string;
    "typeNames": string[];
    "refsValue"?: number | null;
    "refsMatchMode": string;

    /** Creates a new FilterState instance. */
    constructor($$source: Partial<FilterState> = {}) {
        if (!("keyText" in $$source)) {
            this["keyText"] = "";
        }
        if (!("keyMatchMode" in $$source)) {
            this["keyMatchMode"] = "";
        }
        if (!("typeNames" in $$source)) {
            this["typeNames"] = [];
        }
        if (!("refsMatchMode" in $$source)) {
            this["refsMatchMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterState instance from a string or object.
     */
    static createFrom($$source: any = {}): FilterState {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("typeNames" in $$parsedSource) {
            $$parsedSource["typeNames"] = $$createField2_0($$parsedSource["typeNames"]);
        }
        return new FilterState($$parsedSource as Partial<FilterState>);
    }
}

/**
 * FilteredSortedPage is the result of FilterAndSortPage: one page of items and total count.
 */
export class FilteredSortedPage {
    "items": InventoryItem[];
    "totalRecords": number;

    /** Creates a new FilteredSortedPage instance. */
    constructor($$source: Partial<FilteredSortedPage> = {}) {
        if (!("items" in $$source)) {
            this["items"] = [];
        }
        if (!("totalRecords" in $$source)) {
            this["totalRecords"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilteredSortedPage instance from a string or object.
     */
    static createFrom($$source: any = {}): FilteredSortedPage {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new FilteredSortedPage($$parsedSource as Partial<FilteredSortedPage>);
    }
}

/**
 * InventoryItem represents a single extracted game object with metadata.
 */
export class InventoryItem {
    /**
     * Key is the unique identifier for this object (e.g., character ID, event name)
     */
    "key": string;

    /**
     * Type is the object type (e.g., "characters", "events", "traits")
     */
    "type": string;

    /**
     * FilePath is the relative path to the file containing this object
     */
    "filePath": string;

    /**
     * LineStart is the line number where the object definition begins
     */
    "lineStart": number;

    /**
     * LineEnd is the line number where the object definition ends
     */
    "lineEnd": number;

    /**
     * RawText contains the original text of the object definition
     */
    "rawText": string;

    /**
     * References contains resolved references to other objects
     */
    "references"?: ObjectReference[];

    /**
     * Attributes lists attributes in the object body and whether they are present.
     */
    "attributes"?: { [_ in string]?: boolean };

    /** Creates a new InventoryItem instance. */
    constructor($$source: Partial<InventoryItem> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("lineStart" in $$source)) {
            this["lineStart"] = 0;
        }
        if (!("lineEnd" in $$source)) {
            this["lineEnd"] = 0;
        }
        if (!("rawText" in $$source)) {
            this["rawText"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventoryItem instance from a string or object.
     */
    static createFrom($$source: any = {}): InventoryItem {
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("references" in $$parsedSource) {
            $$parsedSource["references"] = $$createField6_0($$parsedSource["references"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField7_0($$parsedSource["attributes"]);
        }
        return new InventoryItem($$parsedSource as Partial<InventoryItem>);
    }
}

/**
 * ObjectReference represents a reference between two game objects
 */
export class ObjectReference {
    /**
     * TargetKey is the key of the referenced object
     */
    "targetKey": string;

    /**
     * TargetType is the type of the referenced object
     */
    "targetType": string;

    /**
     * Context describes where the reference was found (e.g., property name like "holder", "father")
     */
    "context": string;

    /**
     * SourceFile is the file where the reference was found
     */
    "sourceFile": string;

    /**
     * SourceLine is the line number where the reference was found
     */
    "sourceLine": number;

    /** Creates a new ObjectReference instance. */
    constructor($$source: Partial<ObjectReference> = {}) {
        if (!("targetKey" in $$source)) {
            this["targetKey"] = "";
        }
        if (!("targetType" in $$source)) {
            this["targetType"] = "";
        }
        if (!("context" in $$source)) {
            this["context"] = "";
        }
        if (!("sourceFile" in $$source)) {
            this["sourceFile"] = "";
        }
        if (!("sourceLine" in $$source)) {
            this["sourceLine"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectReference instance from a string or object.
     */
    static createFrom($$source: any = {}): ObjectReference {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjectReference($$parsedSource as Partial<ObjectReference>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = InventoryItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ObjectReference.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
