// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DbService manages the SQLite database.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * ResetData wipes all user data (inventories, doc cache, patchnotes) but preserves app_settings. Re-seeds game constants.
 */
export function ResetData(): $CancellablePromise<void> {
    return $Call.ByID(2362858724);
}
