// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiffService provides structured diffs between two files (line-based, with line numbers).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDiff returns a structured diff between two files (DiffLine slice with type, content, line numbers).
 * Uses line-based diff to avoid cascading false positives when only a block of lines changes (e.g. removing comments at the top).
 */
export function GetDiff(beforeFilePath: string, afterFilePath: string): $CancellablePromise<$models.DiffLine[]> {
    return $Call.ByID(1927805179, beforeFilePath, afterFilePath).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.DiffLine.createFrom;
const $$createType1 = $Create.Array($$createType0);
