// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService provides directory/file selection dialogs and game script root / doc path discovery.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuildTree builds a file tree from a list of paths
 */
export function BuildTree(paths: string[]): $CancellablePromise<$models.TreeNode[]> {
    return $Call.ByID(4120140263, paths).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * CollectAndMatchPaths collects files from both paths and returns matching pairs.
 */
export function CollectAndMatchPaths(pathA: string, pathB: string, filter: $models.FileCollectorFilter, matchByFilenameOnly: boolean): $CancellablePromise<{ [_ in string]?: $models.PathMatch }> {
    return $Call.ByID(1380774949, pathA, pathB, filter, matchByFilenameOnly).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * CollectFilesFromPath collects all .txt files from a mix of files and directories
 * Returns a map of relativePath -> fullPath
 */
export function CollectFilesFromPath(inputPath: string, filter: $models.FileCollectorFilter): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(2863705307, inputPath, filter).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * FindMatchingPaths finds paths that exist in both sets. When matchByFilenameOnly is true,
 * matches only by filename (e.g. for zz_mod_file.txt where paths differ).
 */
export function FindMatchingPaths(filesA: { [_ in string]?: string }, filesB: { [_ in string]?: string }, matchByFilenameOnly: boolean): $CancellablePromise<{ [_ in string]?: $models.PathMatch }> {
    return $Call.ByID(2990739391, filesA, filesB, matchByFilenameOnly).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetGameScriptRoot(game: string, installPath: string): $CancellablePromise<string> {
    return $Call.ByID(4081809646, game, installPath);
}

/**
 * GetUserDownloadsDir returns the user's Downloads directory (e.g. ~/Downloads).
 */
export function GetUserDownloadsDir(): $CancellablePromise<string> {
    return $Call.ByID(1105998516);
}

/**
 * ReadFileContent reads a file as UTF-8 text.
 */
export function ReadFileContent(fullPath: string): $CancellablePromise<string> {
    return $Call.ByID(1203948956, fullPath);
}

export function SaveFile(title: string, defaultName: string, content: string, ext: string): $CancellablePromise<string> {
    return $Call.ByID(3260874390, title, defaultName, content, ext);
}

export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(421942968, title);
}

export function SelectSingleFile(title: string, filter: string): $CancellablePromise<string> {
    return $Call.ByID(430312767, title, filter);
}

/**
 * WriteWithBOM writes content to outputPath as UTF-8 with BOM. Creates parent directories as needed.
 */
export function WriteWithBOM(outputPath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(239287030, outputPath, content);
}

// Private type creation functions
const $$createType0 = $models.TreeNode.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.PathMatch.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
