// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService provides directory/file selection dialogs and game script root / doc path discovery.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CollectFilesFromPaths collects all .txt files from a mix of files and directories
 * Returns a map of relativePath -> fullPath
 * For individual files, uses the filename as the relative path
 * For directories, uses the relative path from the directory root
 */
export function CollectFilesFromPaths(paths: string[]): $CancellablePromise<{ [_: string]: string }> {
    return $Call.ByID(1545587832, paths).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * FindMatchingFiles finds files that exist in both sets by matching relative paths
 * Returns a map of relativePath -> FileMatch
 */
export function FindMatchingFiles(filesA: { [_: string]: string }, filesB: { [_: string]: string }): $CancellablePromise<{ [_: string]: $models.FileMatch }> {
    return $Call.ByID(3781625008, filesA, filesB).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetScriptRoot returns the game script root directory for the given game and install path.
 * CK3: <install>/game, EU5: <install>/game/in_game.
 */
export function GetScriptRoot(installPath: string, game: string): $CancellablePromise<string> {
    return $Call.ByID(2313931968, installPath, game);
}

/**
 * ListGameDocFiles walks the game script root and collects .info (CK3) or readme.txt (EU5) files.
 */
export function ListGameDocFiles(game: string, installPath: string): $CancellablePromise<$models.DocFileEntry[]> {
    return $Call.ByID(1629466670, game, installPath).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * OpenFolder opens the given folder path in the system file manager (e.g. Explorer on Windows, Finder on macOS).
 */
export function OpenFolder(folderPath: string): $CancellablePromise<void> {
    return $Call.ByID(2316467521, folderPath);
}

/**
 * ReadFileContent reads a file as UTF-8 text.
 */
export function ReadFileContent(fullPath: string): $CancellablePromise<string> {
    return $Call.ByID(1203948956, fullPath);
}

/**
 * SaveFile sets where to save a file via dialog and writes the content to the file.
 * Returns ("", nil) when the user cancels so no error dialog is shown.
 */
export function SaveFile(defaultName: string, fileType: string, content: string): $CancellablePromise<string> {
    return $Call.ByID(3260874390, defaultName, fileType, content);
}

/**
 * SelectDirectories opens a directory selection dialog allowing multiple selections.
 * Returns (nil, nil) when the user cancels so no error dialog is shown.
 */
export function SelectDirectories(title: string): $CancellablePromise<string[]> {
    return $Call.ByID(2349219276, title).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SelectDirectory opens a directory selection dialog.
 * Returns ("", nil) when the user cancels so no error dialog is shown.
 */
export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(421942968, title);
}

/**
 * SelectFiles opens a file selection dialog allowing multiple selections.
 * Returns (nil, nil) when the user cancels so no error dialog is shown.
 */
export function SelectFiles(title: string, filter: string): $CancellablePromise<string[]> {
    return $Call.ByID(362567264, title, filter).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SelectSingleFile opens a file selection dialog for a single file.
 * Returns ("", nil) when the user cancels so no error dialog is shown.
 */
export function SelectSingleFile(title: string, filter: string): $CancellablePromise<string> {
    return $Call.ByID(430312767, title, filter);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.FileMatch.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $models.DocFileEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
