// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService provides directory/file selection dialogs and game script root / doc path discovery.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CollectFilesFromPaths collects all .txt files from a mix of files and directories
 * Returns a map of relativePath -> fullPath
 */
export function CollectFilesFromPaths(inputPaths: string[], filter: $models.FileCollectorFilter): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1545587832, inputPaths, filter).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * FindMatchingPaths finds paths that exist in both sets by matching relative paths
 * Returns a map of relativePath -> PathMatch
 */
export function FindMatchingPaths(filesA: { [_ in string]?: string }, filesB: { [_ in string]?: string }): $CancellablePromise<{ [_ in string]?: $models.PathMatch }> {
    return $Call.ByID(2990739391, filesA, filesB).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetScriptRoot returns the game script root directory for the given game and install path.
 * CK3: <install>/game, EU5: <install>/game/in_game.
 */
export function GetGameScriptRoot(game: string, installPath: string): $CancellablePromise<string> {
    return $Call.ByID(4081809646, game, installPath);
}

/**
 * ListGameDocFiles walks the game script root and collects .info (CK3) or readme.txt (EU5) files.
 */
export function ListGameDocFiles(game: string, installPath: string): $CancellablePromise<$models.DocFileEntry[]> {
    return $Call.ByID(1629466670, game, installPath).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * ReadFileContent reads a file as UTF-8 text.
 */
export function ReadFileContent(fullPath: string): $CancellablePromise<string> {
    return $Call.ByID(1203948956, fullPath);
}

/**
 * SelectDirectories opens a directory selection dialog allowing multiple selections.
 * Returns (nil, nil) when the user cancels so no error dialog is shown.
 */
export function SelectDirectories(title: string): $CancellablePromise<string[]> {
    return $Call.ByID(2349219276, title).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SelectDirectory opens a directory selection dialog.
 * Returns ("", nil) when the user cancels so no error dialog is shown.
 */
export function SelectDirectory(title: string): $CancellablePromise<string> {
    return $Call.ByID(421942968, title);
}

/**
 * SelectFiles opens a file selection dialog allowing multiple selections.
 * Returns (nil, nil) when the user cancels so no error dialog is shown.
 */
export function SelectFiles(title: string, filter: string): $CancellablePromise<string[]> {
    return $Call.ByID(362567264, title, filter).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SelectSingleFile opens a file selection dialog for a single file.
 * Returns ("", nil) when the user cancels so no error dialog is shown.
 */
export function SelectSingleFile(title: string, filter: string): $CancellablePromise<string> {
    return $Call.ByID(430312767, title, filter);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.PathMatch.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $models.DocFileEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
