// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InventoryService exposes inventory functionality to the Wails frontend (supported types, schema, extraction, cancel).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExtractInventory extracts inventory items from the given basePaths that match the given objectTypes.
 * Only .txt files are processed. Returns items and parse errors or a fatal error if cancelled or too many parse failures.
 */
export function ExtractInventory(game: string, basePaths: string[], objectTypes: string[]): $CancellablePromise<$models.InventoryItem[]> {
    return $Call.ByID(383781064, game, basePaths, objectTypes).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetAttributes returns the list of attribute names for an object type and game.
 */
export function GetAttributes(game: string, typeName: string): $CancellablePromise<string[]> {
    return $Call.ByID(3409867136, game, typeName).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSupportedTypes returns the sorted list of object type names for the given game.
 */
export function GetSupportedTypes(game: string): $CancellablePromise<string[]> {
    return $Call.ByID(1823722162, game).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.InventoryItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
