// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InventoryService exposes inventory functionality to the Wails frontend (supported types, schema, extraction, cancel).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as inventory$0 from "./internal/inventory/models.js";

/**
 * CancelExtraction signals the running ExtractInventory to stop and discard results (immediate, clears in-memory data).
 */
export function CancelExtraction(): $CancellablePromise<void> {
    return $Call.ByID(2645923500);
}

/**
 * ExtractInventory extracts multiple object types from files with references resolved.
 * Returns items keyed by type and any parse errors. Returns inventory.ErrExtractionCancelled if the user cancelled.
 */
export function ExtractInventory(game: string, files: string[], objectTypes: string[]): $CancellablePromise<void> {
    return $Call.ByID(383781064, game, files, objectTypes);
}

/**
 * GetAttributes returns attribute names for an object type (from schema).
 */
export function GetAttributes(game: string, typeName: string): $CancellablePromise<string[]> {
    return $Call.ByID(3409867136, game, typeName).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetFilteredSortedPage returns one page of filtered and sorted inventory items from the stored extract result.
 */
export function GetFilteredSortedPage(filterState: inventory$0.FilterState, sortField: string, sortOrder: number, first: number, rows: number): $CancellablePromise<inventory$0.FilteredSortedPage | null> {
    return $Call.ByID(2427132672, filterState, sortField, sortOrder, first, rows).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSupportedTypes returns the sorted list of object type names for the given game.
 */
export function GetSupportedTypes(game: string): $CancellablePromise<string[]> {
    return $Call.ByID(1823722162, game).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = inventory$0.FilteredSortedPage.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
