// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService writes error logs to a file alongside the DB.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * LogError appends a timestamped error line to pmt-errors.log.
 */
export function LogError(message: string, stack: string): $CancellablePromise<void> {
    return $Call.ByID(1904466489, message, stack);
}
