// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MergeService merges matching script files from two path sets into an output directory using core merge logic.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelMerge signals any running multi-file merge to stop. Partial results may be returned.
 */
export function CancelMerge(): $CancellablePromise<void> {
    return $Call.ByID(1785905195);
}

/**
 * MergeMultipleFileSets merges matching files from pathsA and pathsB into outputDir.
 * Uses core for discovery/matching and merge logic.
 */
export function MergeMultipleFileSets(pathsA: string[], pathsB: string[], outputDir: string, options: $models.MergerOptions): $CancellablePromise<$models.FileMergeResult[]> {
    return $Call.ByID(2908210642, pathsA, pathsB, outputDir, options).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * MergeTwoFiles merges two files and returns the merged content.
 */
export function MergeTwoFiles(fileAPath: string, fileBPath: string, options: $models.MergerOptions): $CancellablePromise<string> {
    return $Call.ByID(3807305580, fileAPath, fileBPath, options);
}

/**
 * MergeTwoFilesAndSave merges two files, opens the save dialog, and writes the result. Single backend call.
 */
export function MergeTwoFilesAndSave(fileAPath: string, fileBPath: string, options: $models.MergerOptions): $CancellablePromise<string> {
    return $Call.ByID(1515496208, fileAPath, fileBPath, options);
}

/**
 * MergeVanillaMod runs the full vanilla-vs-mod merge: resolves game script root, then merges into outputDir.
 * Single backend call for the frontend. Supports cancellation via CancelMerge.
 */
export function MergeVanillaMod(game: string, installPath: string, modPaths: string[], outputDir: string, options: $models.MergerOptions): $CancellablePromise<$models.FileMergeResult[]> {
    return $Call.ByID(1897491292, game, installPath, modPaths, outputDir, options).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.FileMergeResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
