// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings holds persisted app settings (JSON-safe for bindings).
 */
export class AppSettings {
    "gameInstallPathCk3": string;
    "gameInstallPathEu5": string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("gameInstallPathCk3" in $$source)) {
            this["gameInstallPathCk3"] = "";
        }
        if (!("gameInstallPathEu5" in $$source)) {
            this["gameInstallPathEu5"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * DiffLine represents a single line in a diff
 */
export class DiffLine {
    /**
     * "header", "add", "remove", "context", "other"
     */
    "type": string;

    /**
     * The line content
     */
    "content": string;

    /**
     * Line number in old file (nil if not applicable)
     */
    "oldLineNum": number | null;

    /**
     * Line number in new file (nil if not applicable)
     */
    "newLineNum": number | null;

    /** Creates a new DiffLine instance. */
    constructor($$source: Partial<DiffLine> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            this["content"] = "";
        }
        if (!("oldLineNum" in $$source)) {
            this["oldLineNum"] = null;
        }
        if (!("newLineNum" in $$source)) {
            this["newLineNum"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffLine instance from a string or object.
     */
    static createFrom($$source: any = {}): DiffLine {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffLine($$parsedSource as Partial<DiffLine>);
    }
}

/**
 * DocFileEntry represents a doc file found under the game script root (JSON-safe for bindings).
 */
export class DocFileEntry {
    "relativePath": string;
    "fullPath": string;

    /** Creates a new DocFileEntry instance. */
    constructor($$source: Partial<DocFileEntry> = {}) {
        if (!("relativePath" in $$source)) {
            this["relativePath"] = "";
        }
        if (!("fullPath" in $$source)) {
            this["fullPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocFileEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): DocFileEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocFileEntry($$parsedSource as Partial<DocFileEntry>);
    }
}

/**
 * DocPathCache is the cached doc path list for a game+install path (JSON-safe for bindings).
 */
export class DocPathCache {
    "paths": string[];
    "scannedAt": string;
    "installPath": string;
    "lastSeenUpdateId"?: string;

    /** Creates a new DocPathCache instance. */
    constructor($$source: Partial<DocPathCache> = {}) {
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }
        if (!("scannedAt" in $$source)) {
            this["scannedAt"] = "";
        }
        if (!("installPath" in $$source)) {
            this["installPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocPathCache instance from a string or object.
     */
    static createFrom($$source: any = {}): DocPathCache {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField0_0($$parsedSource["paths"]);
        }
        return new DocPathCache($$parsedSource as Partial<DocPathCache>);
    }
}

/**
 * DocPathCacheSet is the payload for setting the doc path cache (installPath added server-side).
 */
export class DocPathCacheSet {
    "paths": string[];
    "scannedAt": string;
    "lastSeenUpdateId"?: string;

    /** Creates a new DocPathCacheSet instance. */
    constructor($$source: Partial<DocPathCacheSet> = {}) {
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }
        if (!("scannedAt" in $$source)) {
            this["scannedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocPathCacheSet instance from a string or object.
     */
    static createFrom($$source: any = {}): DocPathCacheSet {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField0_0($$parsedSource["paths"]);
        }
        return new DocPathCacheSet($$parsedSource as Partial<DocPathCacheSet>);
    }
}

/**
 * FileMatch represents a matched file pair
 */
export class FileMatch {
    "fileAPath": string;
    "fileBPath": string;

    /** Creates a new FileMatch instance. */
    constructor($$source: Partial<FileMatch> = {}) {
        if (!("fileAPath" in $$source)) {
            this["fileAPath"] = "";
        }
        if (!("fileBPath" in $$source)) {
            this["fileBPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): FileMatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileMatch($$parsedSource as Partial<FileMatch>);
    }
}

/**
 * LatestPatchNotes is the latest patch notes entry for a game (JSON-safe for bindings).
 */
export class LatestPatchNotes {
    "url": string;
    "title": string;
    "description": string;

    /** Creates a new LatestPatchNotes instance. */
    constructor($$source: Partial<LatestPatchNotes> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LatestPatchNotes instance from a string or object.
     */
    static createFrom($$source: any = {}): LatestPatchNotes {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LatestPatchNotes($$parsedSource as Partial<LatestPatchNotes>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
