// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as repos$0 from "./internal/repos/models.js";

/**
 * DocPathCache is the cached doc path list for a game+install path (JSON-safe for bindings).
 */
export class DocPathCache {
    "paths": string[];
    "scannedAt": string;
    "installPath": string;

    /** Creates a new DocPathCache instance. */
    constructor($$source: Partial<DocPathCache> = {}) {
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }
        if (!("scannedAt" in $$source)) {
            this["scannedAt"] = "";
        }
        if (!("installPath" in $$source)) {
            this["installPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocPathCache instance from a string or object.
     */
    static createFrom($$source: any = {}): DocPathCache {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField0_0($$parsedSource["paths"]);
        }
        return new DocPathCache($$parsedSource as Partial<DocPathCache>);
    }
}

export class FileCollectorFilter {
    /**
     * e.g. [".txt", ".lua"]
     */
    "Extensions": string[];

    /**
     * e.g. ["readme.txt", "mod.lua"]
     */
    "FileNames": string[];

    /**
     * e.g. "^(readme|mod)\.txt$"
     */
    "Regex": string;

    /**
     * regex on rel path, e.g. "events/" - include only if matches
     */
    "IncludePath": string;

    /**
     * regex on rel path, e.g. "common/" - exclude if matches
     */
    "ExcludePath": string;

    /** Creates a new FileCollectorFilter instance. */
    constructor($$source: Partial<FileCollectorFilter> = {}) {
        if (!("Extensions" in $$source)) {
            this["Extensions"] = [];
        }
        if (!("FileNames" in $$source)) {
            this["FileNames"] = [];
        }
        if (!("Regex" in $$source)) {
            this["Regex"] = "";
        }
        if (!("IncludePath" in $$source)) {
            this["IncludePath"] = "";
        }
        if (!("ExcludePath" in $$source)) {
            this["ExcludePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileCollectorFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): FileCollectorFilter {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Extensions" in $$parsedSource) {
            $$parsedSource["Extensions"] = $$createField0_0($$parsedSource["Extensions"]);
        }
        if ("FileNames" in $$parsedSource) {
            $$parsedSource["FileNames"] = $$createField1_0($$parsedSource["FileNames"]);
        }
        return new FileCollectorFilter($$parsedSource as Partial<FileCollectorFilter>);
    }
}

/**
 * FileMergeResult is the result of merging one file (JSON-safe for bindings)
 */
export class FileMergeResult {
    "filePath": string;
    "fileAPath": string;
    "fileBPath": string;
    "outputPath": string;
    "changed": number;
    "added": number;
    "entriesChanged"?: string[];
    "entriesAdded"?: string[];
    "resolvedConflicts"?: ResolvedConflict[];
    "error"?: string;

    /** Creates a new FileMergeResult instance. */
    constructor($$source: Partial<FileMergeResult> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("fileAPath" in $$source)) {
            this["fileAPath"] = "";
        }
        if (!("fileBPath" in $$source)) {
            this["fileBPath"] = "";
        }
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }
        if (!("changed" in $$source)) {
            this["changed"] = 0;
        }
        if (!("added" in $$source)) {
            this["added"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileMergeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FileMergeResult {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType0;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entriesChanged" in $$parsedSource) {
            $$parsedSource["entriesChanged"] = $$createField6_0($$parsedSource["entriesChanged"]);
        }
        if ("entriesAdded" in $$parsedSource) {
            $$parsedSource["entriesAdded"] = $$createField7_0($$parsedSource["entriesAdded"]);
        }
        if ("resolvedConflicts" in $$parsedSource) {
            $$parsedSource["resolvedConflicts"] = $$createField8_0($$parsedSource["resolvedConflicts"]);
        }
        return new FileMergeResult($$parsedSource as Partial<FileMergeResult>);
    }
}

export const InventoryItemRow = repos$0.InventoryItemRow;
export type InventoryItemRow = repos$0.InventoryItemRow;

export const InventorySummary = repos$0.InventorySummary;
export type InventorySummary = repos$0.InventorySummary;

export const ItemDetails = repos$0.ItemDetails;
export type ItemDetails = repos$0.ItemDetails;

/**
 * LatestPatchNotes is the latest patch notes entry for a game (JSON-safe for bindings).
 */
export class LatestPatchNotes {
    "url": string;
    "title": string;
    "contents": string;

    /** Creates a new LatestPatchNotes instance. */
    constructor($$source: Partial<LatestPatchNotes> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("contents" in $$source)) {
            this["contents"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LatestPatchNotes instance from a string or object.
     */
    static createFrom($$source: any = {}): LatestPatchNotes {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LatestPatchNotes($$parsedSource as Partial<LatestPatchNotes>);
    }
}

/**
 * MergeConflictChunk is a unit of content for the assisted merge editor (and internal merge iteration).
 * ObjA/ObjB are internal-only; JSON output omits them.
 */
export class MergeConflictChunk {
    /**
     * "unchanged", "added", or "conflict"
     */
    "type": string;
    "textA": string;
    "textB": string;
    "startLineA": number;
    "startLineB": number;
    "endLineA": number;
    "endLineB": number;

    /** Creates a new MergeConflictChunk instance. */
    constructor($$source: Partial<MergeConflictChunk> = {}) {
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("textA" in $$source)) {
            this["textA"] = "";
        }
        if (!("textB" in $$source)) {
            this["textB"] = "";
        }
        if (!("startLineA" in $$source)) {
            this["startLineA"] = 0;
        }
        if (!("startLineB" in $$source)) {
            this["startLineB"] = 0;
        }
        if (!("endLineA" in $$source)) {
            this["endLineA"] = 0;
        }
        if (!("endLineB" in $$source)) {
            this["endLineB"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeConflictChunk instance from a string or object.
     */
    static createFrom($$source: any = {}): MergeConflictChunk {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeConflictChunk($$parsedSource as Partial<MergeConflictChunk>);
    }
}

/**
 * MergePair is a user-specified file pair (JSON-safe for bindings)
 */
export class MergePair {
    "pathA": string;
    "pathB": string;

    /**
     * e.g. "merged_events.txt"; empty = use PathA basename
     */
    "outputName": string;

    /** Creates a new MergePair instance. */
    constructor($$source: Partial<MergePair> = {}) {
        if (!("pathA" in $$source)) {
            this["pathA"] = "";
        }
        if (!("pathB" in $$source)) {
            this["pathB"] = "";
        }
        if (!("outputName" in $$source)) {
            this["outputName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergePair instance from a string or object.
     */
    static createFrom($$source: any = {}): MergePair {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergePair($$parsedSource as Partial<MergePair>);
    }
}

/**
 * MergePreset holds a named merge options profile (JSON-safe for bindings)
 */
export class MergePreset {
    "name": string;
    "options": MergerOptions;

    /** Creates a new MergePreset instance. */
    constructor($$source: Partial<MergePreset> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = (new MergerOptions());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergePreset instance from a string or object.
     */
    static createFrom($$source: any = {}): MergePreset {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField1_0($$parsedSource["options"]);
        }
        return new MergePreset($$parsedSource as Partial<MergePreset>);
    }
}

/**
 * MergerOptions configures how files are merged (JSON-safe for bindings)
 */
export class MergerOptions {
    "addAdditionalEntries": boolean;
    "manualConflictResolution": boolean;
    "keyList": string[];
    "matchByFilenameOnly": boolean;
    "includePathPattern": string;
    "excludePathPattern": string;
    "outputFilename": string;

    /**
     * e.g. "_merged" meaning: events/foo.txt -> events/foo_merged.txt
     */
    "outputFileSuffix": string;

    /** Creates a new MergerOptions instance. */
    constructor($$source: Partial<MergerOptions> = {}) {
        if (!("addAdditionalEntries" in $$source)) {
            this["addAdditionalEntries"] = false;
        }
        if (!("manualConflictResolution" in $$source)) {
            this["manualConflictResolution"] = false;
        }
        if (!("keyList" in $$source)) {
            this["keyList"] = [];
        }
        if (!("matchByFilenameOnly" in $$source)) {
            this["matchByFilenameOnly"] = false;
        }
        if (!("includePathPattern" in $$source)) {
            this["includePathPattern"] = "";
        }
        if (!("excludePathPattern" in $$source)) {
            this["excludePathPattern"] = "";
        }
        if (!("outputFilename" in $$source)) {
            this["outputFilename"] = "";
        }
        if (!("outputFileSuffix" in $$source)) {
            this["outputFileSuffix"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergerOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MergerOptions {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keyList" in $$parsedSource) {
            $$parsedSource["keyList"] = $$createField2_0($$parsedSource["keyList"]);
        }
        return new MergerOptions($$parsedSource as Partial<MergerOptions>);
    }
}

/**
 * FileMatch represents a matched path pair
 */
export class PathMatch {
    "pathA": string;
    "pathB": string;

    /** Creates a new PathMatch instance. */
    constructor($$source: Partial<PathMatch> = {}) {
        if (!("pathA" in $$source)) {
            this["pathA"] = "";
        }
        if (!("pathB" in $$source)) {
            this["pathB"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): PathMatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathMatch($$parsedSource as Partial<PathMatch>);
    }
}

/**
 * PreviewItem is a single file match for the merge preview (JSON-safe for bindings)
 */
export class PreviewItem {
    "relPath": string;
    "pathA": string;
    "pathB": string;
    "outputPath": string;
    "wouldOverwrite": boolean;

    /** Creates a new PreviewItem instance. */
    constructor($$source: Partial<PreviewItem> = {}) {
        if (!("relPath" in $$source)) {
            this["relPath"] = "";
        }
        if (!("pathA" in $$source)) {
            this["pathA"] = "";
        }
        if (!("pathB" in $$source)) {
            this["pathB"] = "";
        }
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }
        if (!("wouldOverwrite" in $$source)) {
            this["wouldOverwrite"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PreviewItem instance from a string or object.
     */
    static createFrom($$source: any = {}): PreviewItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PreviewItem($$parsedSource as Partial<PreviewItem>);
    }
}

/**
 * ResolvedConflict records a conflict that was auto-resolved (for report/audit).
 */
export class ResolvedConflict {
    "key": string;

    /**
     * "A" or "B"
     */
    "usedSide": string;

    /**
     * "directive", "keyList", "default"
     */
    "reason": string;

    /** Creates a new ResolvedConflict instance. */
    constructor($$source: Partial<ResolvedConflict> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("usedSide" in $$source)) {
            this["usedSide"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolvedConflict instance from a string or object.
     */
    static createFrom($$source: any = {}): ResolvedConflict {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResolvedConflict($$parsedSource as Partial<ResolvedConflict>);
    }
}

export class TreeNode {
    "relPath": string;
    "name": string;
    "children": TreeNode[];

    /** Creates a new TreeNode instance. */
    constructor($$source: Partial<TreeNode> = {}) {
        if (!("relPath" in $$source)) {
            this["relPath"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): TreeNode {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField2_0($$parsedSource["children"]);
        }
        return new TreeNode($$parsedSource as Partial<TreeNode>);
    }
}

/**
 * ValidationError describes a parse error in a merged file (JSON-safe for bindings)
 */
export class ValidationError {
    "path": string;
    "line": number;
    "error": string;

    /** Creates a new ValidationError instance. */
    constructor($$source: Partial<ValidationError> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("line" in $$source)) {
            this["line"] = 0;
        }
        if (!("error" in $$source)) {
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationError instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidationError {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ValidationError($$parsedSource as Partial<ValidationError>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ResolvedConflict.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = MergerOptions.createFrom;
const $$createType4 = TreeNode.createFrom;
const $$createType5 = $Create.Array($$createType4);
