// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings holds persisted app settings and game constants (JSON-safe for bindings).
 */
export class AppSettings {
    "gameInstallPathCk3": string;
    "gameInstallPathEu5": string;
    "ck3_steamAppId": string;
    "ck3_wikiUrl": string;
    "ck3_scriptRootFolder": string;
    "ck3_docFileName": string;
    "eu5_steamAppId": string;
    "eu5_wikiUrl": string;
    "eu5_scriptRootFolder": string;
    "eu5_docFileName": string;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("gameInstallPathCk3" in $$source)) {
            this["gameInstallPathCk3"] = "";
        }
        if (!("gameInstallPathEu5" in $$source)) {
            this["gameInstallPathEu5"] = "";
        }
        if (!("ck3_steamAppId" in $$source)) {
            this["ck3_steamAppId"] = "";
        }
        if (!("ck3_wikiUrl" in $$source)) {
            this["ck3_wikiUrl"] = "";
        }
        if (!("ck3_scriptRootFolder" in $$source)) {
            this["ck3_scriptRootFolder"] = "";
        }
        if (!("ck3_docFileName" in $$source)) {
            this["ck3_docFileName"] = "";
        }
        if (!("eu5_steamAppId" in $$source)) {
            this["eu5_steamAppId"] = "";
        }
        if (!("eu5_wikiUrl" in $$source)) {
            this["eu5_wikiUrl"] = "";
        }
        if (!("eu5_scriptRootFolder" in $$source)) {
            this["eu5_scriptRootFolder"] = "";
        }
        if (!("eu5_docFileName" in $$source)) {
            this["eu5_docFileName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

/**
 * DocPathCache is the cached doc path list for a game+install path (JSON-safe for bindings).
 */
export class DocPathCache {
    "paths": string[];
    "scannedAt": string;
    "installPath": string;

    /** Creates a new DocPathCache instance. */
    constructor($$source: Partial<DocPathCache> = {}) {
        if (!("paths" in $$source)) {
            this["paths"] = [];
        }
        if (!("scannedAt" in $$source)) {
            this["scannedAt"] = "";
        }
        if (!("installPath" in $$source)) {
            this["installPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocPathCache instance from a string or object.
     */
    static createFrom($$source: any = {}): DocPathCache {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField0_0($$parsedSource["paths"]);
        }
        return new DocPathCache($$parsedSource as Partial<DocPathCache>);
    }
}

/**
 * ExtractInventoryResult is returned by ExtractInventory after saving to DB.
 */
export class ExtractInventoryResult {
    "inventoryId": string;
    "totalCount": number;

    /** Creates a new ExtractInventoryResult instance. */
    constructor($$source: Partial<ExtractInventoryResult> = {}) {
        if (!("inventoryId" in $$source)) {
            this["inventoryId"] = "";
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtractInventoryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExtractInventoryResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExtractInventoryResult($$parsedSource as Partial<ExtractInventoryResult>);
    }
}

export class FileCollectorFilter {
    /**
     * e.g. [".txt", ".lua"]
     */
    "Extensions": string[];

    /**
     * e.g. ["readme.txt", "mod.lua"]
     */
    "FileNames": string[];

    /**
     * e.g. "^(readme|mod)\.txt$"
     */
    "Regex": string;

    /** Creates a new FileCollectorFilter instance. */
    constructor($$source: Partial<FileCollectorFilter> = {}) {
        if (!("Extensions" in $$source)) {
            this["Extensions"] = [];
        }
        if (!("FileNames" in $$source)) {
            this["FileNames"] = [];
        }
        if (!("Regex" in $$source)) {
            this["Regex"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileCollectorFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): FileCollectorFilter {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Extensions" in $$parsedSource) {
            $$parsedSource["Extensions"] = $$createField0_0($$parsedSource["Extensions"]);
        }
        if ("FileNames" in $$parsedSource) {
            $$parsedSource["FileNames"] = $$createField1_0($$parsedSource["FileNames"]);
        }
        return new FileCollectorFilter($$parsedSource as Partial<FileCollectorFilter>);
    }
}

/**
 * FileMergeResult is the result of merging one file (JSON-safe for bindings)
 */
export class FileMergeResult {
    "filePath": string;
    "fileAPath": string;
    "fileBPath": string;
    "outputPath": string;
    "changed": number;
    "added": number;
    "removed": number;
    "error"?: string;

    /** Creates a new FileMergeResult instance. */
    constructor($$source: Partial<FileMergeResult> = {}) {
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("fileAPath" in $$source)) {
            this["fileAPath"] = "";
        }
        if (!("fileBPath" in $$source)) {
            this["fileBPath"] = "";
        }
        if (!("outputPath" in $$source)) {
            this["outputPath"] = "";
        }
        if (!("changed" in $$source)) {
            this["changed"] = 0;
        }
        if (!("added" in $$source)) {
            this["added"] = 0;
        }
        if (!("removed" in $$source)) {
            this["removed"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileMergeResult instance from a string or object.
     */
    static createFrom($$source: any = {}): FileMergeResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileMergeResult($$parsedSource as Partial<FileMergeResult>);
    }
}

/**
 * InventoryItemRow is a lightweight grid row (key, type, file_path, lines, counts).
 */
export class InventoryItemRow {
    "key": string;
    "type": string;
    "filePath": string;
    "lineStart": number;
    "lineEnd": number;
    "referencesCount": number;
    "referrersCount": number;

    /** Creates a new InventoryItemRow instance. */
    constructor($$source: Partial<InventoryItemRow> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("lineStart" in $$source)) {
            this["lineStart"] = 0;
        }
        if (!("lineEnd" in $$source)) {
            this["lineEnd"] = 0;
        }
        if (!("referencesCount" in $$source)) {
            this["referencesCount"] = 0;
        }
        if (!("referrersCount" in $$source)) {
            this["referrersCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventoryItemRow instance from a string or object.
     */
    static createFrom($$source: any = {}): InventoryItemRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InventoryItemRow($$parsedSource as Partial<InventoryItemRow>);
    }
}

/**
 * InventorySummary is a lightweight inventory listing (for ListInventories).
 */
export class InventorySummary {
    "id": string;
    "name": string;
    "game": string;
    "createdAt": string;
    "totalCount": number;

    /** Creates a new InventorySummary instance. */
    constructor($$source: Partial<InventorySummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("game" in $$source)) {
            this["game"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventorySummary instance from a string or object.
     */
    static createFrom($$source: any = {}): InventorySummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InventorySummary($$parsedSource as Partial<InventorySummary>);
    }
}

/**
 * ItemDetails is the full details for a single item (for GetItemDetails).
 */
export class ItemDetails {
    "rawText": string;
    "references": ObjectReference[];
    "referrers": ObjectReference[];
    "attributes": { [_ in string]?: boolean };

    /** Creates a new ItemDetails instance. */
    constructor($$source: Partial<ItemDetails> = {}) {
        if (!("rawText" in $$source)) {
            this["rawText"] = "";
        }
        if (!("references" in $$source)) {
            this["references"] = [];
        }
        if (!("referrers" in $$source)) {
            this["referrers"] = [];
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemDetails {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("references" in $$parsedSource) {
            $$parsedSource["references"] = $$createField1_0($$parsedSource["references"]);
        }
        if ("referrers" in $$parsedSource) {
            $$parsedSource["referrers"] = $$createField2_0($$parsedSource["referrers"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField3_0($$parsedSource["attributes"]);
        }
        return new ItemDetails($$parsedSource as Partial<ItemDetails>);
    }
}

/**
 * LatestPatchNotes is the latest patch notes entry for a game (JSON-safe for bindings).
 */
export class LatestPatchNotes {
    "url": string;
    "title": string;
    "contents": string;

    /** Creates a new LatestPatchNotes instance. */
    constructor($$source: Partial<LatestPatchNotes> = {}) {
        if (!("url" in $$source)) {
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("contents" in $$source)) {
            this["contents"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LatestPatchNotes instance from a string or object.
     */
    static createFrom($$source: any = {}): LatestPatchNotes {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LatestPatchNotes($$parsedSource as Partial<LatestPatchNotes>);
    }
}

/**
 * MergerOptions configures how files are merged (JSON-safe for bindings)
 */
export class MergerOptions {
    "addAdditionalEntries": boolean;
    "entryPlacement": string;
    "keyList": string[];
    "customCommentPrefix": string;

    /** Creates a new MergerOptions instance. */
    constructor($$source: Partial<MergerOptions> = {}) {
        if (!("addAdditionalEntries" in $$source)) {
            this["addAdditionalEntries"] = false;
        }
        if (!("entryPlacement" in $$source)) {
            this["entryPlacement"] = "";
        }
        if (!("keyList" in $$source)) {
            this["keyList"] = [];
        }
        if (!("customCommentPrefix" in $$source)) {
            this["customCommentPrefix"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergerOptions instance from a string or object.
     */
    static createFrom($$source: any = {}): MergerOptions {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keyList" in $$parsedSource) {
            $$parsedSource["keyList"] = $$createField2_0($$parsedSource["keyList"]);
        }
        return new MergerOptions($$parsedSource as Partial<MergerOptions>);
    }
}

/**
 * ObjectReference represents a reference between two game objects.
 */
export class ObjectReference {
    "key": string;
    "type": string;
    "filePath": string;
    "lineStart"?: number;
    "lineEnd"?: number;

    /** Creates a new ObjectReference instance. */
    constructor($$source: Partial<ObjectReference> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectReference instance from a string or object.
     */
    static createFrom($$source: any = {}): ObjectReference {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjectReference($$parsedSource as Partial<ObjectReference>);
    }
}

/**
 * FileMatch represents a matched path pair
 */
export class PathMatch {
    "pathA": string;
    "pathB": string;

    /** Creates a new PathMatch instance. */
    constructor($$source: Partial<PathMatch> = {}) {
        if (!("pathA" in $$source)) {
            this["pathA"] = "";
        }
        if (!("pathB" in $$source)) {
            this["pathB"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PathMatch instance from a string or object.
     */
    static createFrom($$source: any = {}): PathMatch {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PathMatch($$parsedSource as Partial<PathMatch>);
    }
}

export class TreeNode {
    "relPath": string;
    "name": string;
    "children": TreeNode[];

    /** Creates a new TreeNode instance. */
    constructor($$source: Partial<TreeNode> = {}) {
        if (!("relPath" in $$source)) {
            this["relPath"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("children" in $$source)) {
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeNode instance from a string or object.
     */
    static createFrom($$source: any = {}): TreeNode {
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField2_0($$parsedSource["children"]);
        }
        return new TreeNode($$parsedSource as Partial<TreeNode>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ObjectReference.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Map($Create.Any, $Create.Any);
const $$createType4 = TreeNode.createFrom;
const $$createType5 = $Create.Array($$createType4);
