// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService provides persisted app settings, doc path cache, and latest patch notes (SteamDB RSS).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearDocPathCache removes the doc path cache entry for the game+install path.
 */
export function ClearDocPathCache(game: string, installPath: string): $CancellablePromise<void> {
    return $Call.ByID(286048698, game, installPath);
}

/**
 * GetDocPathCache returns the cached doc path list for the game+install path, or nil if not found.
 */
export function GetDocPathCache(game: string, installPath: string): $CancellablePromise<$models.DocPathCache | null> {
    return $Call.ByID(3297201731, game, installPath).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetLatestPatchNotes returns the latest patch notes URL and title for the game, using SteamDB RSS.
 * Caches the result for 7 days in patchnotes-cache.json.
 */
export function GetLatestPatchNotes(game: string): $CancellablePromise<$models.LatestPatchNotes> {
    return $Call.ByID(1048142926, game).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSettings loads settings from disk. Returns default values if file does not exist.
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1419253203).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * SaveSettings writes settings to disk.
 */
export function SaveSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(3145424170, settings);
}

/**
 * SetDocPathCache writes the doc path cache for the game+install path to disk (same dir as settings).
 */
export function SetDocPathCache(game: string, installPath: string, data: $models.DocPathCacheSet): $CancellablePromise<void> {
    return $Call.ByID(3964679767, game, installPath, data);
}

// Private type creation functions
const $$createType0 = $models.DocPathCache.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.LatestPatchNotes.createFrom;
const $$createType3 = $models.AppSettings.createFrom;
