// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService provides persisted app settings, doc path cache, and latest patch notes (SteamDB RSS).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetLatestPatchNotes returns the latest patch notes URL and title for the game, using SteamDB RSS.
 * Caches the result for 7 days in patchnotes-cache.json.
 */
export function GetLatestPatchNotes(game: string): $CancellablePromise<$models.LatestPatchNotes> {
    return $Call.ByID(1048142926, game).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * GetSettings loads settings from disk. Returns default values if file does not exist.
 */
export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(1419253203).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * SaveSettings writes settings to disk.
 */
export function SaveSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(3145424170, settings);
}

// Private type creation functions
const $$createType0 = $models.LatestPatchNotes.createFrom;
const $$createType1 = $models.AppSettings.createFrom;
