// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService provides persisted app settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteMergePreset removes a preset by name.
 */
export function DeleteMergePreset(name: string): $CancellablePromise<void> {
    return $Call.ByID(241571328, name);
}

/**
 * GetMergePresets returns saved merge presets from app_settings.
 */
export function GetMergePresets(): $CancellablePromise<$models.MergePreset[]> {
    return $Call.ByID(3580251362).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSettings loads settings as a map "game.key" -> value.
 */
export function GetSettings(): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(1419253203).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SaveMergePreset saves a merge preset by name.
 */
export function SaveMergePreset(name: string, options: $models.MergerOptions): $CancellablePromise<void> {
    return $Call.ByID(3311953510, name, options);
}

/**
 * SaveSettings writes user settings to app_settings table.
 */
export function SaveSettings(settings: { [_ in string]?: string }): $CancellablePromise<void> {
    return $Call.ByID(3145424170, settings);
}

// Private type creation functions
const $$createType0 = $models.MergePreset.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
