// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ExtractResult is the return type of ExtractInventory (inventory + precomputed graph)
 */
export class ExtractResult {
    /**
     * Creates a new ExtractResult instance.
     * @param {Partial<ExtractResult>} [$$source = {}] - The source object to create the ExtractResult.
     */
    constructor($$source = {}) {
        if (!("inventory" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: InventoryResult | null }}
             */
            this["inventory"] = {};
        }
        if (!("graph" in $$source)) {
            /**
             * @member
             * @type {GraphData | null}
             */
            this["graph"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExtractResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExtractResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        const $$createField1_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inventory" in $$parsedSource) {
            $$parsedSource["inventory"] = $$createField0_0($$parsedSource["inventory"]);
        }
        if ("graph" in $$parsedSource) {
            $$parsedSource["graph"] = $$createField1_0($$parsedSource["graph"]);
        }
        return new ExtractResult(/** @type {Partial<ExtractResult>} */($$parsedSource));
    }
}

/**
 * GraphData is the precomputed reference graph for the frontend
 */
export class GraphData {
    /**
     * Creates a new GraphData instance.
     * @param {Partial<GraphData>} [$$source = {}] - The source object to create the GraphData.
     */
    constructor($$source = {}) {
        if (!("nodes" in $$source)) {
            /**
             * @member
             * @type {GraphNode[]}
             */
            this["nodes"] = [];
        }
        if (!("links" in $$source)) {
            /**
             * @member
             * @type {GraphLink[]}
             */
            this["links"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField0_0($$parsedSource["nodes"]);
        }
        if ("links" in $$parsedSource) {
            $$parsedSource["links"] = $$createField1_0($$parsedSource["links"]);
        }
        return new GraphData(/** @type {Partial<GraphData>} */($$parsedSource));
    }
}

/**
 * GraphLink represents an edge in the reference graph
 */
export class GraphLink {
    /**
     * Creates a new GraphLink instance.
     * @param {Partial<GraphLink>} [$$source = {}] - The source object to create the GraphLink.
     */
    constructor($$source = {}) {
        if (!("source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphLink instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphLink}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphLink(/** @type {Partial<GraphLink>} */($$parsedSource));
    }
}

/**
 * GraphNode represents a node in the reference graph (for ECharts)
 */
export class GraphNode {
    /**
     * Creates a new GraphNode instance.
     * @param {Partial<GraphNode>} [$$source = {}] - The source object to create the GraphNode.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["category"] = 0;
        }
        if (!("symbolSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["symbolSize"] = 0;
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GraphNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GraphNode}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GraphNode(/** @type {Partial<GraphNode>} */($$parsedSource));
    }
}

/**
 * InventoryItem represents a single extracted game object with metadata
 */
export class InventoryItem {
    /**
     * Creates a new InventoryItem instance.
     * @param {Partial<InventoryItem>} [$$source = {}] - The source object to create the InventoryItem.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * Key is the unique identifier for this object (e.g., character ID, event name)
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * Type is the object type (e.g., "characters", "events", "traits")
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * FilePath is the relative path to the file containing this object
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("lineStart" in $$source)) {
            /**
             * LineStart is the line number where the object definition begins
             * @member
             * @type {number}
             */
            this["lineStart"] = 0;
        }
        if (!("lineEnd" in $$source)) {
            /**
             * LineEnd is the line number where the object definition ends
             * @member
             * @type {number}
             */
            this["lineEnd"] = 0;
        }
        if (!("rawText" in $$source)) {
            /**
             * RawText contains the original text of the object definition
             * @member
             * @type {string}
             */
            this["rawText"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * References contains resolved references to other objects
             * @member
             * @type {ObjectReference[] | undefined}
             */
            this["references"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventoryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InventoryItem}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("references" in $$parsedSource) {
            $$parsedSource["references"] = $$createField6_0($$parsedSource["references"]);
        }
        return new InventoryItem(/** @type {Partial<InventoryItem>} */($$parsedSource));
    }
}

/**
 * InventoryResult contains the results of an inventory operation
 */
export class InventoryResult {
    /**
     * Creates a new InventoryResult instance.
     * @param {Partial<InventoryResult>} [$$source = {}] - The source object to create the InventoryResult.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * Type is the object type that was inventoried
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("totalCount" in $$source)) {
            /**
             * TotalCount is the total number of objects found
             * @member
             * @type {number}
             */
            this["totalCount"] = 0;
        }
        if (!("items" in $$source)) {
            /**
             * Items contains all extracted objects
             * @member
             * @type {InventoryItem[]}
             */
            this["items"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * Errors contains any non-fatal errors encountered during extraction
             * @member
             * @type {string[] | undefined}
             */
            this["errors"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventoryResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InventoryResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType12;
        const $$createField3_0 = $$createType13;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField2_0($$parsedSource["items"]);
        }
        if ("errors" in $$parsedSource) {
            $$parsedSource["errors"] = $$createField3_0($$parsedSource["errors"]);
        }
        return new InventoryResult(/** @type {Partial<InventoryResult>} */($$parsedSource));
    }
}

/**
 * ObjectReference represents a reference between two game objects
 */
export class ObjectReference {
    /**
     * Creates a new ObjectReference instance.
     * @param {Partial<ObjectReference>} [$$source = {}] - The source object to create the ObjectReference.
     */
    constructor($$source = {}) {
        if (!("targetKey" in $$source)) {
            /**
             * TargetKey is the key of the referenced object
             * @member
             * @type {string}
             */
            this["targetKey"] = "";
        }
        if (!("targetType" in $$source)) {
            /**
             * TargetType is the type of the referenced object
             * @member
             * @type {string}
             */
            this["targetType"] = "";
        }
        if (!("context" in $$source)) {
            /**
             * Context describes where the reference was found (e.g., property name like "holder", "father")
             * @member
             * @type {string}
             */
            this["context"] = "";
        }
        if (!("sourceFile" in $$source)) {
            /**
             * SourceFile is the file where the reference was found
             * @member
             * @type {string}
             */
            this["sourceFile"] = "";
        }
        if (!("sourceLine" in $$source)) {
            /**
             * SourceLine is the line number where the reference was found
             * @member
             * @type {number}
             */
            this["sourceLine"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectReference instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ObjectReference}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjectReference(/** @type {Partial<ObjectReference>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = InventoryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = GraphData.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = GraphNode.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = GraphLink.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ObjectReference.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = InventoryItem.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Array($Create.Any);
