// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowserService opens URLs in the system default browser (Windows, macOS, Linux).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * OpenURL opens the given URL in the user's default browser.
 * Works on Windows (cmd /c start), macOS (open), and Linux (xdg-open).
 */
export function OpenURL(url: string): $CancellablePromise<void> {
    return $Call.ByID(1630691376, url);
}
