// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SteamService centralizes Steam API integrations: patch notes (News API) now, depot/build API later.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetLatestPatchNotes returns the latest patch notes for the game using Steam News API.
 * Uses patchnotes table; fetches from API if stale or missing. Description is a short preview.
 */
export function GetLatestPatchNotes(game: string): $CancellablePromise<$models.LatestPatchNotes> {
    return $Call.ByID(3933143665, game).then(($result: any) => {
        return $$createType0($result);
    });
}

// Private type creation functions
const $$createType0 = $models.LatestPatchNotes.createFrom;
