// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FilterState is the filter state for table filtering and export (same shape as frontend).
 */
export class FilterState {
    /**
     * Creates a new FilterState instance.
     * @param {Partial<FilterState>} [$$source = {}] - The source object to create the FilterState.
     */
    constructor($$source = {}) {
        if (!("keyText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyText"] = "";
        }
        if (!("keyMatchMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyMatchMode"] = "";
        }
        if (!("typeNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["typeNames"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | null | undefined}
             */
            this["refsValue"] = undefined;
        }
        if (!("refsMatchMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refsMatchMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilterState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FilterState}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("typeNames" in $$parsedSource) {
            $$parsedSource["typeNames"] = $$createField2_0($$parsedSource["typeNames"]);
        }
        return new FilterState(/** @type {Partial<FilterState>} */($$parsedSource));
    }
}

/**
 * FilteredSortedPage is the result of FilterAndSortPage: one page of items and total count.
 */
export class FilteredSortedPage {
    /**
     * Creates a new FilteredSortedPage instance.
     * @param {Partial<FilteredSortedPage>} [$$source = {}] - The source object to create the FilteredSortedPage.
     */
    constructor($$source = {}) {
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {InventoryItem[]}
             */
            this["items"] = [];
        }
        if (!("totalRecords" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalRecords"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FilteredSortedPage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FilteredSortedPage}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new FilteredSortedPage(/** @type {Partial<FilteredSortedPage>} */($$parsedSource));
    }
}

/**
 * InventoryItem represents a single extracted game object with metadata.
 */
export class InventoryItem {
    /**
     * Creates a new InventoryItem instance.
     * @param {Partial<InventoryItem>} [$$source = {}] - The source object to create the InventoryItem.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * Key is the unique identifier for this object (e.g., character ID, event name)
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * Type is the object type (e.g., "characters", "events", "traits")
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("filePath" in $$source)) {
            /**
             * FilePath is the relative path to the file containing this object
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("lineStart" in $$source)) {
            /**
             * LineStart is the line number where the object definition begins
             * @member
             * @type {number}
             */
            this["lineStart"] = 0;
        }
        if (!("lineEnd" in $$source)) {
            /**
             * LineEnd is the line number where the object definition ends
             * @member
             * @type {number}
             */
            this["lineEnd"] = 0;
        }
        if (!("rawText" in $$source)) {
            /**
             * RawText contains the original text of the object definition
             * @member
             * @type {string}
             */
            this["rawText"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * References contains resolved references to other objects
             * @member
             * @type {ObjectReference[] | undefined}
             */
            this["references"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Attributes lists attributes in the object body and whether they are present.
             * @member
             * @type {{ [_: string]: boolean } | undefined}
             */
            this["attributes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventoryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {InventoryItem}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("references" in $$parsedSource) {
            $$parsedSource["references"] = $$createField6_0($$parsedSource["references"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField7_0($$parsedSource["attributes"]);
        }
        return new InventoryItem(/** @type {Partial<InventoryItem>} */($$parsedSource));
    }
}

/**
 * ObjectReference represents a reference between two game objects
 */
export class ObjectReference {
    /**
     * Creates a new ObjectReference instance.
     * @param {Partial<ObjectReference>} [$$source = {}] - The source object to create the ObjectReference.
     */
    constructor($$source = {}) {
        if (!("targetKey" in $$source)) {
            /**
             * TargetKey is the key of the referenced object
             * @member
             * @type {string}
             */
            this["targetKey"] = "";
        }
        if (!("targetType" in $$source)) {
            /**
             * TargetType is the type of the referenced object
             * @member
             * @type {string}
             */
            this["targetType"] = "";
        }
        if (!("context" in $$source)) {
            /**
             * Context describes where the reference was found (e.g., property name like "holder", "father")
             * @member
             * @type {string}
             */
            this["context"] = "";
        }
        if (!("sourceFile" in $$source)) {
            /**
             * SourceFile is the file where the reference was found
             * @member
             * @type {string}
             */
            this["sourceFile"] = "";
        }
        if (!("sourceLine" in $$source)) {
            /**
             * SourceLine is the line number where the reference was found
             * @member
             * @type {number}
             */
            this["sourceLine"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectReference instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ObjectReference}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjectReference(/** @type {Partial<ObjectReference>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = InventoryItem.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ObjectReference.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
