// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiffService provides diff functionality for comparing files
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetDiff generates a structured diff between two files
 * Returns an array of DiffLine objects with type, content, and line numbers
 * @param {string} beforeFilePath
 * @param {string} afterFilePath
 * @returns {$CancellablePromise<$models.DiffLine[]>}
 */
export function GetDiff(beforeFilePath, afterFilePath) {
    return $Call.ByID(238570749, beforeFilePath, afterFilePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.DiffLine.createFrom;
const $$createType1 = $Create.Array($$createType0);
