// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService provides directory/file selection dialogs and game script root / doc path discovery.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as inventory$0 from "./internal/inventory/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CollectFilesFromPaths collects all .txt files from a mix of files and directories
 * Returns a map of relativePath -> fullPath
 * For individual files, uses the filename as the relative path
 * For directories, uses the relative path from the directory root
 * @param {string[]} paths
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function CollectFilesFromPaths(paths) {
    return $Call.ByID(2993640142, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ExportInventoryFromBackend uses the given extraction result, applies filterState, optionally fills raw text, shows folder dialog, and writes the file.
 * Returns the path of the written file, or ("", nil) if the user cancels, or ("", err) if no inventory or write failure.
 * @param {inventory$0.ExtractResult | null} extractResult
 * @param {inventory$0.FilterState} filterState
 * @param {string} format
 * @param {boolean} includeRawText
 * @returns {$CancellablePromise<string>}
 */
export function ExportInventoryFromBackend(extractResult, filterState, format, includeRawText) {
    return $Call.ByID(2655947101, extractResult, filterState, format, includeRawText);
}

/**
 * FindMatchingFiles finds files that exist in both sets by matching relative paths
 * Returns a map of relativePath -> FileMatch
 * @param {{ [_: string]: string }} filesA
 * @param {{ [_: string]: string }} filesB
 * @returns {$CancellablePromise<{ [_: string]: $models.FileMatch }>}
 */
export function FindMatchingFiles(filesA, filesB) {
    return $Call.ByID(2437198750, filesA, filesB).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetScriptRoot returns the game script root directory for the given game and install path.
 * CK3: <install>/game, EU5: <install>/game/in_game.
 * @param {string} installPath
 * @param {string} game
 * @returns {$CancellablePromise<string>}
 */
export function GetScriptRoot(installPath, game) {
    return $Call.ByID(4003673982, installPath, game);
}

/**
 * ListGameDocFiles walks the game script root and collects .info (CK3) or readme.txt (EU5) files.
 * @param {string} game
 * @param {string} installPath
 * @returns {$CancellablePromise<$models.DocFileEntry[]>}
 */
export function ListGameDocFiles(game, installPath) {
    return $Call.ByID(3866316244, game, installPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * OpenFolder opens the given folder path in the system file manager (e.g. Explorer on Windows, Finder on macOS).
 * @param {string} folderPath
 * @returns {$CancellablePromise<void>}
 */
export function OpenFolder(folderPath) {
    return $Call.ByID(2206639011, folderPath);
}

/**
 * ReadFileContent reads a file as UTF-8 text.
 * @param {string} fullPath
 * @returns {$CancellablePromise<string>}
 */
export function ReadFileContent(fullPath) {
    return $Call.ByID(97925398, fullPath);
}

/**
 * SaveFile sets where to save a file via dialog and writes the content to the file.
 * Returns ("", nil) when the user cancels so no error dialog is shown.
 * @param {string} defaultName
 * @param {string} fileType
 * @param {string} content
 * @returns {$CancellablePromise<string>}
 */
export function SaveFile(defaultName, fileType, content) {
    return $Call.ByID(2283414560, defaultName, fileType, content);
}

/**
 * SelectDirectory opens a directory selection dialog.
 * Returns ("", nil) when the user cancels so no error dialog is shown.
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory(title) {
    return $Call.ByID(3212470570, title);
}

/**
 * SelectMultipleFiles opens a file selection dialog allowing multiple file selection.
 * Returns (nil, nil) when the user cancels so no error dialog is shown.
 * @param {string} title
 * @param {string} filter
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectMultipleFiles(title, filter) {
    return $Call.ByID(3216870446, title, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SelectSingleFile opens a file selection dialog for a single file.
 * Returns ("", nil) when the user cancels so no error dialog is shown.
 * @param {string} title
 * @param {string} filter
 * @returns {$CancellablePromise<string>}
 */
export function SelectSingleFile(title, filter) {
    return $Call.ByID(2176788877, title, filter);
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.FileMatch.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $models.DocFileEntry.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
