// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FileService provides file selection and collection operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CollectFilesFromPaths collects all .txt files from a mix of files and directories
 * Returns a map of relativePath -> fullPath
 * For individual files, uses the filename as the relative path
 * For directories, uses the relative path from the directory root
 * @param {string[]} paths
 * @returns {$CancellablePromise<{ [_: string]: string }>}
 */
export function CollectFilesFromPaths(paths) {
    return $Call.ByID(2993640142, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * FindMatchingFiles finds files that exist in both sets by matching relative paths
 * Returns a map of relativePath -> FileMatch
 * @param {{ [_: string]: string }} filesA
 * @param {{ [_: string]: string }} filesB
 * @returns {$CancellablePromise<{ [_: string]: $models.FileMatch }>}
 */
export function FindMatchingFiles(filesA, filesB) {
    return $Call.ByID(2437198750, filesA, filesB).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SelectDirectory opens a directory selection dialog.
 * Returns ("", nil) when the user cancels so no error dialog is shown.
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function SelectDirectory(title) {
    return $Call.ByID(3212470570, title);
}

/**
 * SelectMultipleFiles opens a file selection dialog allowing multiple file selection.
 * Returns (nil, nil) when the user cancels so no error dialog is shown.
 * @param {string} title
 * @param {string} filter
 * @returns {$CancellablePromise<string[]>}
 */
export function SelectMultipleFiles(title, filter) {
    return $Call.ByID(3216870446, title, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $models.FileMatch.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = $Create.Array($Create.Any);
