// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InventoryService exposes inventory functionality to the Wails frontend (supported types, schema, extraction, cancel).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as inventory$0 from "./internal/inventory/models.js";

/**
 * CancelExtraction signals the running ExtractInventory to stop and discard results (immediate, clears in-memory data).
 * @returns {$CancellablePromise<void>}
 */
export function CancelExtraction() {
    return $Call.ByID(743443218);
}

/**
 * ExtractInventory extracts multiple object types from files with references resolved.
 * Returns items keyed by type and any parse errors. Returns inventory.ErrExtractionCancelled if the user cancelled.
 * @param {string} game
 * @param {string[]} files
 * @param {string[]} objectTypes
 * @returns {$CancellablePromise<inventory$0.ExtractResult | null>}
 */
export function ExtractInventory(game, files, objectTypes) {
    return $Call.ByID(4163016662, game, files, objectTypes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAttributes returns attribute names for an object type (from schema).
 * @param {string} game
 * @param {string} typeName
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAttributes(game, typeName) {
    return $Call.ByID(3349659334, game, typeName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetFilteredSortedPage returns one page of filtered and sorted inventory items for the results table.
 * @param {inventory$0.ExtractResult | null} result
 * @param {inventory$0.FilterState} filterState
 * @param {string} sortField
 * @param {number} sortOrder
 * @param {number} first
 * @param {number} rows
 * @returns {$CancellablePromise<inventory$0.FilteredSortedPage | null>}
 */
export function GetFilteredSortedPage(result, filterState, sortField, sortOrder, first, rows) {
    return $Call.ByID(1776626858, result, filterState, sortField, sortOrder, first, rows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetSupportedTypes returns the sorted list of object type names for the given game.
 * @param {string} game
 * @returns {$CancellablePromise<string[]>}
 */
export function GetSupportedTypes(game) {
    return $Call.ByID(840319924, game).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = inventory$0.ExtractResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = inventory$0.FilteredSortedPage.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
