// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InventoryService provides inventory functionality for Paradox game objects
 * Exposed to the Wails frontend
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as inventory$0 from "./internal/inventory/models.js";

/**
 * ExtractInventory extracts multiple object types from files with references resolved
 * and precomputes the reference graph.
 * Returns ExtractResult with Inventory (map of type -> InventoryResult) and Graph (nodes + links).
 * @param {string} game
 * @param {string[]} files
 * @param {string[]} objectTypes
 * @returns {$CancellablePromise<inventory$0.ExtractResult | null>}
 */
export function ExtractInventory(game, files, objectTypes) {
    return $Call.ByID(4163016662, game, files, objectTypes).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetSupportedGames returns a list of supported game identifiers
 * @returns {$CancellablePromise<string[]>}
 */
export function GetSupportedGames() {
    return $Call.ByID(1695770698).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSupportedTypes returns object types available for a specific game
 * @param {string} game
 * @returns {$CancellablePromise<string[]>}
 */
export function GetSupportedTypes(game) {
    return $Call.ByID(840319924, game).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = inventory$0.ExtractResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
