// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MergerService provides script merge operations
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * MergeMultipleFileSets merges matching files from pathsA and pathsB into outputDir.
 * Uses core for discovery/matching and merge logic.
 * @param {string[]} pathsA
 * @param {string[]} pathsB
 * @param {string} outputDir
 * @param {$models.MergerOptions} options
 * @returns {$CancellablePromise<$models.FileMergeResult[]>}
 */
export function MergeMultipleFileSets(pathsA, pathsB, outputDir, options) {
    return $Call.ByID(721497370, pathsA, pathsB, outputDir, options).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * MergeTwoFiles merges two files and returns the merged content. The frontend uses SaveFile to write it to a user-chosen path.
 * @param {string} fileAPath
 * @param {string} fileBPath
 * @param {$models.MergerOptions} options
 * @returns {$CancellablePromise<string>}
 */
export function MergeTwoFiles(fileAPath, fileBPath, options) {
    return $Call.ByID(3948444292, fileAPath, fileBPath, options);
}

// Private type creation functions
const $$createType0 = $models.FileMergeResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
