// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DiffLine represents a single line in a diff
 */
export class DiffLine {
    /**
     * Creates a new DiffLine instance.
     * @param {Partial<DiffLine>} [$$source = {}] - The source object to create the DiffLine.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "header", "add", "remove", "context", "other"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * The line content
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("oldLineNum" in $$source)) {
            /**
             * Line number in old file (nil if not applicable)
             * @member
             * @type {number | null}
             */
            this["oldLineNum"] = null;
        }
        if (!("newLineNum" in $$source)) {
            /**
             * Line number in new file (nil if not applicable)
             * @member
             * @type {number | null}
             */
            this["newLineNum"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffLine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffLine}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffLine(/** @type {Partial<DiffLine>} */($$parsedSource));
    }
}

/**
 * FileMatch represents a matched file pair
 */
export class FileMatch {
    /**
     * Creates a new FileMatch instance.
     * @param {Partial<FileMatch>} [$$source = {}] - The source object to create the FileMatch.
     */
    constructor($$source = {}) {
        if (!("fileAPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileAPath"] = "";
        }
        if (!("fileBPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileBPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileMatch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileMatch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileMatch(/** @type {Partial<FileMatch>} */($$parsedSource));
    }
}
