// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppSettings holds persisted app settings (JSON-safe for bindings).
 */
export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("game" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["game"] = "";
        }
        if (!("gameInstallPathCk3" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gameInstallPathCk3"] = "";
        }
        if (!("gameInstallPathEu5" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gameInstallPathEu5"] = "";
        }
        if (!("patchNotesFeedUrlCk3" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["patchNotesFeedUrlCk3"] = "";
        }
        if (!("patchNotesFeedUrlEu5" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["patchNotesFeedUrlEu5"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

/**
 * DiffLine represents a single line in a diff
 */
export class DiffLine {
    /**
     * Creates a new DiffLine instance.
     * @param {Partial<DiffLine>} [$$source = {}] - The source object to create the DiffLine.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * "header", "add", "remove", "context", "other"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * The line content
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("oldLineNum" in $$source)) {
            /**
             * Line number in old file (nil if not applicable)
             * @member
             * @type {number | null}
             */
            this["oldLineNum"] = null;
        }
        if (!("newLineNum" in $$source)) {
            /**
             * Line number in new file (nil if not applicable)
             * @member
             * @type {number | null}
             */
            this["newLineNum"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiffLine instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiffLine}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiffLine(/** @type {Partial<DiffLine>} */($$parsedSource));
    }
}

/**
 * DocFileEntry represents a doc file found under the game script root (JSON-safe for bindings).
 */
export class DocFileEntry {
    /**
     * Creates a new DocFileEntry instance.
     * @param {Partial<DocFileEntry>} [$$source = {}] - The source object to create the DocFileEntry.
     */
    constructor($$source = {}) {
        if (!("relativePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["relativePath"] = "";
        }
        if (!("fullPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fullPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocFileEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocFileEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocFileEntry(/** @type {Partial<DocFileEntry>} */($$parsedSource));
    }
}

/**
 * DocPathCache is the cached doc path list for a game+install path (JSON-safe for bindings).
 */
export class DocPathCache {
    /**
     * Creates a new DocPathCache instance.
     * @param {Partial<DocPathCache>} [$$source = {}] - The source object to create the DocPathCache.
     */
    constructor($$source = {}) {
        if (!("paths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["paths"] = [];
        }
        if (!("scannedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scannedAt"] = "";
        }
        if (!("installPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["installPath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastSeenUpdateId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocPathCache instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocPathCache}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField0_0($$parsedSource["paths"]);
        }
        return new DocPathCache(/** @type {Partial<DocPathCache>} */($$parsedSource));
    }
}

/**
 * DocPathCacheSet is the payload for setting the doc path cache (installPath added server-side).
 */
export class DocPathCacheSet {
    /**
     * Creates a new DocPathCacheSet instance.
     * @param {Partial<DocPathCacheSet>} [$$source = {}] - The source object to create the DocPathCacheSet.
     */
    constructor($$source = {}) {
        if (!("paths" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["paths"] = [];
        }
        if (!("scannedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scannedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["lastSeenUpdateId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocPathCacheSet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocPathCacheSet}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("paths" in $$parsedSource) {
            $$parsedSource["paths"] = $$createField0_0($$parsedSource["paths"]);
        }
        return new DocPathCacheSet(/** @type {Partial<DocPathCacheSet>} */($$parsedSource));
    }
}

/**
 * FileMatch represents a matched file pair
 */
export class FileMatch {
    /**
     * Creates a new FileMatch instance.
     * @param {Partial<FileMatch>} [$$source = {}] - The source object to create the FileMatch.
     */
    constructor($$source = {}) {
        if (!("fileAPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileAPath"] = "";
        }
        if (!("fileBPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileBPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileMatch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileMatch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileMatch(/** @type {Partial<FileMatch>} */($$parsedSource));
    }
}

/**
 * FileMergeResult is the result of merging one file (JSON-safe for bindings)
 */
export class FileMergeResult {
    /**
     * Creates a new FileMergeResult instance.
     * @param {Partial<FileMergeResult>} [$$source = {}] - The source object to create the FileMergeResult.
     */
    constructor($$source = {}) {
        if (!("filePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filePath"] = "";
        }
        if (!("fileAPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileAPath"] = "";
        }
        if (!("fileBPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fileBPath"] = "";
        }
        if (!("outputPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["outputPath"] = "";
        }
        if (!("changed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["changed"] = 0;
        }
        if (!("added" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["added"] = 0;
        }
        if (!("removed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["removed"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileMergeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileMergeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileMergeResult(/** @type {Partial<FileMergeResult>} */($$parsedSource));
    }
}

/**
 * LatestPatchNotes is the latest patch notes entry for a game (JSON-safe for bindings).
 */
export class LatestPatchNotes {
    /**
     * Creates a new LatestPatchNotes instance.
     * @param {Partial<LatestPatchNotes>} [$$source = {}] - The source object to create the LatestPatchNotes.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LatestPatchNotes instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LatestPatchNotes}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LatestPatchNotes(/** @type {Partial<LatestPatchNotes>} */($$parsedSource));
    }
}

/**
 * MergerOptions configures how files are merged (JSON-safe for bindings)
 */
export class MergerOptions {
    /**
     * Creates a new MergerOptions instance.
     * @param {Partial<MergerOptions>} [$$source = {}] - The source object to create the MergerOptions.
     */
    constructor($$source = {}) {
        if (!("addAdditionalEntries" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["addAdditionalEntries"] = false;
        }
        if (!("entryPlacement" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entryPlacement"] = "";
        }
        if (!("keyList" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["keyList"] = [];
        }
        if (!("customCommentPrefix" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["customCommentPrefix"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergerOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergerOptions}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("keyList" in $$parsedSource) {
            $$parsedSource["keyList"] = $$createField2_0($$parsedSource["keyList"]);
        }
        return new MergerOptions(/** @type {Partial<MergerOptions>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
