// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService provides persisted app settings, doc path cache, and latest patch notes (SteamDB RSS).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearDocPathCache removes the doc path cache entry for the game+install path.
 * @param {string} game
 * @param {string} installPath
 * @returns {$CancellablePromise<void>}
 */
export function ClearDocPathCache(game, installPath) {
    return $Call.ByID(3594974208, game, installPath);
}

/**
 * GetDocPathCache returns the cached doc path list for the game+install path, or nil if not found.
 * @param {string} game
 * @param {string} installPath
 * @returns {$CancellablePromise<$models.DocPathCache | null>}
 */
export function GetDocPathCache(game, installPath) {
    return $Call.ByID(3621539709, game, installPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetLatestPatchNotes returns the latest patch notes URL and title for the game, using SteamDB RSS.
 * Caches the result for 7 days in patchnotes-cache.json.
 * @param {string} game
 * @returns {$CancellablePromise<$models.LatestPatchNotes>}
 */
export function GetLatestPatchNotes(game) {
    return $Call.ByID(2762062460, game).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetSettings loads settings from disk. Returns default values if file does not exist.
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function GetSettings() {
    return $Call.ByID(3034808949).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SaveSettings writes settings to disk.
 * @param {$models.AppSettings} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(2662658340, settings);
}

/**
 * SetDocPathCache writes the doc path cache for the game+install path to disk (same dir as settings).
 * @param {string} game
 * @param {string} installPath
 * @param {$models.DocPathCacheSet} data
 * @returns {$CancellablePromise<void>}
 */
export function SetDocPathCache(game, installPath, data) {
    return $Call.ByID(282613449, game, installPath, data);
}

// Private type creation functions
const $$createType0 = $models.DocPathCache.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.LatestPatchNotes.createFrom;
const $$createType3 = $models.AppSettings.createFrom;
