// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InventoryItemRow is a lightweight grid row.
 */
export class InventoryItemRow {
    "key": string;
    "type": string;
    "filePath": string;
    "lineStart": number;
    "lineEnd": number;
    "referencesCount": number;
    "referrersCount": number;

    /** Creates a new InventoryItemRow instance. */
    constructor($$source: Partial<InventoryItemRow> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }
        if (!("lineStart" in $$source)) {
            this["lineStart"] = 0;
        }
        if (!("lineEnd" in $$source)) {
            this["lineEnd"] = 0;
        }
        if (!("referencesCount" in $$source)) {
            this["referencesCount"] = 0;
        }
        if (!("referrersCount" in $$source)) {
            this["referrersCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventoryItemRow instance from a string or object.
     */
    static createFrom($$source: any = {}): InventoryItemRow {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InventoryItemRow($$parsedSource as Partial<InventoryItemRow>);
    }
}

/**
 * InventorySummary is a lightweight inventory listing.
 */
export class InventorySummary {
    "id": string;
    "name": string;
    "game": string;
    "createdAt": string;
    "totalCount": number;

    /** Creates a new InventorySummary instance. */
    constructor($$source: Partial<InventorySummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("game" in $$source)) {
            this["game"] = "";
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("totalCount" in $$source)) {
            this["totalCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InventorySummary instance from a string or object.
     */
    static createFrom($$source: any = {}): InventorySummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InventorySummary($$parsedSource as Partial<InventorySummary>);
    }
}

/**
 * ItemDetails is the full details for a single item.
 */
export class ItemDetails {
    "rawText": string;
    "references": ObjectReference[];
    "referrers": ObjectReference[];
    "attributes": { [_ in string]?: boolean };

    /** Creates a new ItemDetails instance. */
    constructor($$source: Partial<ItemDetails> = {}) {
        if (!("rawText" in $$source)) {
            this["rawText"] = "";
        }
        if (!("references" in $$source)) {
            this["references"] = [];
        }
        if (!("referrers" in $$source)) {
            this["referrers"] = [];
        }
        if (!("attributes" in $$source)) {
            this["attributes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ItemDetails instance from a string or object.
     */
    static createFrom($$source: any = {}): ItemDetails {
        const $$createField1_0 = $$createType1;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("references" in $$parsedSource) {
            $$parsedSource["references"] = $$createField1_0($$parsedSource["references"]);
        }
        if ("referrers" in $$parsedSource) {
            $$parsedSource["referrers"] = $$createField2_0($$parsedSource["referrers"]);
        }
        if ("attributes" in $$parsedSource) {
            $$parsedSource["attributes"] = $$createField3_0($$parsedSource["attributes"]);
        }
        return new ItemDetails($$parsedSource as Partial<ItemDetails>);
    }
}

/**
 * ObjectReference represents a reference between two game objects.
 */
export class ObjectReference {
    "key": string;
    "type": string;
    "filePath": string;
    "lineStart"?: number;
    "lineEnd"?: number;

    /** Creates a new ObjectReference instance. */
    constructor($$source: Partial<ObjectReference> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("filePath" in $$source)) {
            this["filePath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectReference instance from a string or object.
     */
    static createFrom($$source: any = {}): ObjectReference {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjectReference($$parsedSource as Partial<ObjectReference>);
    }
}

// Private type creation functions
const $$createType0 = ObjectReference.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
